/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CarbonFaceCool: typeof import('~icons/carbon/face-cool')['default']
    CityWeatherCardList: typeof import('./src/components/city-weather-card-list.vue')['default']
    CityWeatherWidget: typeof import('./src/components/city-weather-widget.vue')['default']
    MainPage: typeof import('./src/components/main-page.vue')['default']
    MainPage2: typeof import('./src/components/main-page-2.vue')['default']
    MainPageOptionAPI: typeof import('./src/components/main-page-optionAPI.vue')['default']
    MaterialSymbolsBlindRounded: typeof import('~icons/material-symbols/blind-rounded')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
